version: '3'

services:
  backend:
    build: ./
    restart: always
    environment:
      TRAQ_ORIGIN: http://localhost:3000
      TRAQ_MARIADB_HOST: mysql
      TRAQ_PPROF: "true"
    entrypoint: dockerize -timeout 60s -wait tcp://mysql:3306
    command: ./traQ serve --dev --skip-init-emojis
    expose:
      - "80"
      - "6060"
    ports:
      - "6060:6060"
    depends_on:
      - mysql

  frontend:
    image: caddy:latest
    restart: always
    expose:
      - "80"
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./dev/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./dev/frontend:/usr/share/caddy:ro

  mysql:
    image: mariadb:10.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: traq
    # conohaのDBのデフォルトCharsetはutf8
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:                                                         # ここ追加 
      - db_data:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3002:3306"

  adminer:
    image: adminer:4.7.5
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: nette
    expose:
      - "8080"
    ports:
      - "3001:8080"

  botdebugger:
    image: golang:alpine
    restart: always
    volumes:
      - ./dev/bin:/app
    command: go run /app/bot_debugger.go -p 80
